In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fsolve

In [ ]:
#pregunta 1
print("Variable dependiente: tiempo en milisegundos")
print("Variable independiente: tamaño de lista elementos")
print("pendiente = 3")
print("coef. de posición = 5")

In [ ]:
#pregunta 2
def T(n):
  return 3*n+5
print(f"2) Demora {T(101)} ms")

print("3) El tiempo de ejecución del algoritmo aumenta en 3 milisegundos, por cada elemento adicional en la lista.")

2) Demora 308 ms
3) El tiempo de ejecución del algoritmo aumenta en 3 milisegundos, por cada elemento adicional en la lista.


In [ ]:
#pregunta 4
print(f"El dominio contextualizado  desde 0 a {2013-1985}") #calcular diferencia de años
print("Al transcurrir 8 años, se da la máxima cantidad de socios es de 171 miles de socios")

El dominio contextualizado  desde 0 a 28
Al transcurrir 8 años, se da la máxima cantidad de socios es de 171 miles de socios


In [ ]:
#pregunta 5
x = np.array([5,10,15,20])
y = np.array([200,300,400,500])
#Si la función es de grado 1
m, n = np.polyfit(x, y, 1)
print(f"5) La función es f(x)={m}x-{n:.0f}")

5) La función es f(x)=20.0x-100


In [ ]:
def f(x):
    return 2*1.2**x-20

#Valor/es inicial/es de la aproximación
x = np.linspace(0,100,1)
solucion =(fsolve(f, x))

print(f"6) en {solucion}")

6) en [12.62925314]


In [ ]:
def U(t):
  return 1000*np.exp(0.1*t)
print(f"7) usuarios en {U(12):.0f}")

7) usuarios en 3320


In [ ]:
def A(n):
  return 5*n**3-2*n
print(f"8) Son {A(15)}")

8) Son 16845


In [ ]:
a1=2.1
a2=2.2
a3=2.3
d=a2-a1

def B(n):
  return 2.1+d*(n-1)-5.6
x = np.linspace(0,100,1)
solucion = fsolve(B, n)

print(f"9) Son {solucion}")

9) Son [36.]


In [ ]:
def C(n):
  return 1000+5*(n-1)
print(f"10) {C(25)}")

10) 1120


In [ ]:
print("11) 250+50(n-1)")

11) 250+50(n-1)


In [ ]:
print("12) 20*2**(n-1)")

12) 20*2**(n-1)


In [ ]:
a4=24
a6=96
r=(a6/24)**(1/2)
print(r)
a1=a4/r**(3)
print(f"{a1:.0f}")
a9=a1*r**(9-1)
print(f"13) El termino es {a9}")

2.0
3
13) El termino es 768.0


In [ ]:
a=[]
for i in range(8):
  n=i+1
  a.append (300+40*(n-1))
total=sum(a)
print(f"14) {total}")

14) 3520


In [ ]:
print("15) El estudiante 2 tuvo nota mayor que 4,0 en la asignatura 2.")

15) El estudiante 2 tuvo nota mayor que 4,0 en la asignatura 2.


In [ ]:
print("16) resta - diferencia \n")
A=np.array([[4,6],
            [8,5],
            [2,7]])
B=np.array([[1,7],
            [4,6],
            [6,5]])

S=A+B
print(f"Resultado suma \n{S}")
print("\n17) Falso\n ")

C=1.2*B

print(C)
print("\n18) 6")

16) resta - diferencia 

Resultado suma 
[[ 5 13]
 [12 11]
 [ 8 12]]

17) Falso
 
[[1.2 8.4]
 [4.8 7.2]
 [7.2 6. ]]

18) 6


In [ ]:
def A(i,j):
  return 20*(i+1)*(j+1)
A=np.fromfunction(A,(15,10))

def B(i,j):
  return 4*(i+1)+(j+1)
B=np.fromfunction(B,(10,5))

C=np.dot(A,B)

print(C)

#buscar c83
print("\n19) El total es de 272800 euros")


[[ 31900.  33000.  34100.  35200.  36300.]
 [ 63800.  66000.  68200.  70400.  72600.]
 [ 95700.  99000. 102300. 105600. 108900.]
 [127600. 132000. 136400. 140800. 145200.]
 [159500. 165000. 170500. 176000. 181500.]
 [191400. 198000. 204600. 211200. 217800.]
 [223300. 231000. 238700. 246400. 254100.]
 [255200. 264000. 272800. 281600. 290400.]
 [287100. 297000. 306900. 316800. 326700.]
 [319000. 330000. 341000. 352000. 363000.]
 [350900. 363000. 375100. 387200. 399300.]
 [382800. 396000. 409200. 422400. 435600.]
 [414700. 429000. 443300. 457600. 471900.]
 [446600. 462000. 477400. 492800. 508200.]
 [478500. 495000. 511500. 528000. 544500.]]

19) El total es de 272800 euros


In [ ]:
#pregunta 20
A=np.array([[4,8],
            [2,6]])
B=np.array([[72],
            [40]])
sol=np.linalg.solve(A,B)
print(sol)

[[14.]
 [ 2.]]
